### ISSUE TITLE
Overlapping

### ISSUE THREAD

**Issue by stefanDeveloper** [Niklas-Werner/tikz-feature-model#1]
Sadly, when I add too many children to a node it overlaps.

    \tikzfeaturemodel{12,1}{
        \node [abstract] {Application}
            child [mandatory] { node [abstract] (os) {OS}
                child { node (windows) {Windows} }
                child { node (unix) {Unix} }
            }
            child [mandatory] { node [abstract] (browser) {Browser}
                child { node (firefox) {Firefox} }
                child { node (chrome) {Chrome} }
                child { node (safari) {Safari} }
            }
            child [mandatory] { node [abstract] (layer) {Layer} 
                child { node (Layer1) {Layer1} }
                child { node (Layer2) {Layer2} }
                child { node (Layer3) {Layer3} }
                child { node (Layer4) {Layer4} }
                child { node (Layer5) {Layer5} }
                child { node (Layer6) {Layer6} }
                child { node (Layer7) {Layer7} }
            }
        ;
    
        \alternative{os}{windows}{unix}
        \alternative{browser}{firefox}{safari}
    }

How it looks: 

![Screen Shot 2021-03-08 at 8 05 36 AM](https://user-images.githubusercontent.com/18898803/110286374-1a468680-7fe5-11eb-89e3-c89743d1819a.png)

Is there a way to fix it? Thanks & best regards
Stefan

**Comment by Niklas-Werner** [comment]
You can adjust the distance between nodes by specifying additional TikZ options.
In your example, increase the distance between the level 1 nodes (OS, Browser, Layer):
```tex
\tikzfeaturemodel[
    level 1/.append style = {
        sibling distance = 10em
    }
]{12,1}{
    \node [abstract] {Application}
        child [mandatory] { node [abstract] (os) {OS}
            child { node (windows) {Windows} }
            child { node (unix) {Unix} }
        }
        child [mandatory] { node [abstract] (browser) {Browser}
            child { node (firefox) {Firefox} }
            child { node (chrome) {Chrome} }
            child { node (safari) {Safari} }
        }
        child [mandatory] { node [abstract] (layer) {Layer} 
            child { node (Layer1) {Layer1} }
            child { node (Layer2) {Layer2} }
            child { node (Layer3) {Layer3} }
            child { node (Layer4) {Layer4} }
            child { node (Layer5) {Layer5} }
            child { node (Layer6) {Layer6} }
            child { node (Layer7) {Layer7} }
        }
    ;

    \alternative{os}{windows}{unix}
    \alternative{browser}{firefox}{safari}
}
```

I'd recommend ordering the nodes in a way that avoids too much blank space.
For example, in your picture, I'd probably place "Search" between "Browser" and "Layer".

This is also shown in the ["advanced" example](https://github.com/Niklas-Werner/tikz-feature-model/blob/master/examples/advanced.tex#L15-L18).
The default distances are specified [here](https://github.com/Niklas-Werner/tikz-feature-model/blob/master/tikz-feature-model.tex#L87-L100).
