### ISSUE TITLE
Help with overlapping nodes

### ISSUE THREAD

**Issue by codingfabi** [Niklas-Werner/tikz-feature-model#2]
Hey there, 

I'm currently trying to implement a feature modell for a search engine and I can't get the formatting to work: 

![grafik](https://user-images.githubusercontent.com/17953957/110631149-815f6900-81a6-11eb-8490-721b9cc0b35a.png)

I tried to set the distances between the childs like it is shown in the advanced example, but this doesn't fix the main problems for me. I would be especially interested in a way to move nodes slightly more to the right to avoid horizontal overlapping aswell. 
Here is my latex code: 

\begin{figure}[h]\label{fig:feature modell}
	\centering
	\resizebox{0.94\columnwidth}{!} {
	\tikzfeaturemodel[
		level 1/.append style = {
		sibling distance = 10em
		},
		level 2/.append style = {
		sibling distance = 5em
	}
	]{12,10}{
			\node [abstract] {Suchmaschine}
			child [mandatory] { node [] (Suchanfrageneingabe) {Suchanfrageneingabe}
				child { node [mandatory](sprachunterstützung) {Sprachunterstützung}
					child { node [value] (englisch) {Englisch}
					}
					child { node [value] (deutsch) {Deutsch}
					}	
			 }
				child { node [optional] {Suchvorschlag} 
				}
				child { node [optional] {Schreibkorrektur}
				}
				child { node [optional] {Synonym}
				}
			}
			child [mandatory] { node []{Suchergebnispräsentation} 
				child { node [mandatory] {Tabellarische Präsentation}
						child { node (pageSizes) {Seitengröße} 
							child {node [numeric](pageSize1){10}}
							child {node [numeric](pageSize2){25}}
							child {node [numeric](pageSize1){50}}
						}
					}
				child { node [mandatory] {Suchergebnis}
						child { node [mandatory] {Dateityp}
								child { node [value] {PDF} }	
								child { node [value] {DOCX}}
								child { node [value] {HTML}}
							}
						child { node [mandatory] {Ergebnisvorschau}
							}
						child { node [mandatory] {Datum}
						}
						child { node [mandatory] {Textinhalt}
						}
						child { node [mandatory] {Herkunft}
						}
						}
			}
			child { node [mandatory] (browser) {Browserunterstützung}
				child { node [value](firefox){firefox}}
				child { node [value](chrome){chrome}}
				child { node [value](safari){safari}}	
			}
			;
			
			\alternative{pageSizes}{pageSize1}{pageSize2}{pageSaze3}
			\alternative{browser}{firefox}{chrome}{safari}
			\alternative{sprachunterstützung}{englisch}{deutsch}
		}
	}
	\caption{Feature Modell der Suchmaschine}
\end{figure}

**Comment by Niklas-Werner** [comment]
You were on the right track with the advanced example. In addition to adjustign the sibling distance for more vertical spacing, you will also need to increase the level distance for horizontal spacing.

For nodes with long text I'd recommend using multiline nodes instead of increasing the distances too much, for example:
`child [mandatory] { node [multiline] {Tabellarische\\Präsentation} ... `

**Comment by codingfabi** [comment]
Thanks a lot for the response. This is my code now: 

\begin{figure}[h]\label{fig:feature modell}
	\centering
	\resizebox{0.94\columnwidth}{!} {
	\tikzfeaturemodel[
		level 1/.append style = {
		sibling distance = 20em
		},
		level 2/.append style = {
		level distance = 10em,
		sibling distance = 5em
		},
		level 3/.append style = {
		sibling distance = 4em
		}
	]{12,10}{
			\node [abstract] {Suchmaschine}
			child [mandatory] { node [multiline] (Suchanfrageneingabe) {Eingabe \\ Suchanfrage}
				child { node [mandatory](sprachunterstützung) {Sprachunterstützung}
					child { node [value] (englisch) {Englisch}
					}
					child { node [value] (deutsch) {Deutsch}
					}	
			 }
				child { node [optional] {Suchvorschlag} 
				}
				child { node [optional] {Schreibkorrektur}
				}
				child { node [optional] {Synonym}
				}
			}
			child [mandatory] { node [multiline]{Suchergebnis-\\präsentation} 
				child { node [mandatory, multiline] {Tabellarische\\Präsentation}
						child { node (pageSizes) {Seitengröße} 
							child {node [numeric](pageSize1){10}}
							child {node [numeric](pageSize2){25}}
							child {node [numeric](pageSize1){50}}
						}
					}
				child { node [mandatory] {Suchergebnis}
						child { node [mandatory] {Dateityp}
								child { node [value] {PDF} }	
								child { node [value] {DOCX}}
								child { node [value] {HTML}}
							}
						child { node [mandatory, multiline] {Ergebnis-\\vorschau}
							}
						child { node [mandatory] {Datum}
						}
						child { node [mandatory] {Textinhalt}
						}
						child { node [mandatory] {Herkunft}
						}
						}
			}
			child { node [mandatory] (browser) {Browserunterstützung}
				child { node [value](firefox){firefox}}
				child { node [value](chrome){chrome}}
				child { node [value](safari){safari}}	
			}
			;
			
			\alternative{pageSizes}{pageSize1}{pageSize2}{pageSaze3}
			\alternative{browser}{firefox}{chrome}{safari}
			\alternative{sprachunterstützung}{englisch}{deutsch}
		}
	}
	\caption{Feature Modell der Suchmaschine}
\end{figure}

it is slightly better but still not usable. Increasing the sibling distance over 5em at level 2 breaks the entire model. I guess I'm trying to implement it in some other way. Thank you nevertheless!

**Comment by Niklas-Werner** [comment]
It's just TikZ, there's a lot you can do with it.
I tried moving things around a bit and I think the result doesn't look so bad:
```tex
\tikzfeaturemodel[
    level 1/.append style = {
        sibling distance = 12em
    },
    level 2/.append style = {
        level distance = 10em,
        sibling distance = 2.5em
    },
    level 3/.append style = {
        sibling distance = 2em
    }
]{13,7}{
    \node [abstract] {Suchmaschine}
        child [mandatory] { node [multiline] {Eingabe\\Suchanfrage}
            child [mandatory] { node (sprachunterstuetzung) {Sprachunterstützung}
                child { node [value] (englisch) {Englisch} }
                child { node [value] (deutsch) {Deutsch} }
            }
            child { node [optional] {Suchvorschlag} }
            child { node [optional] {Schreibkorrektur} }
            child { node [optional] {Synonym} }
        }
        child [mandatory] { node [multiline] {Suchergebnis-\\präsentation}
            child { node [mandatory, multiline, above = 2em] {Tabellarische\\Präsentation}
                child { node (pageSizes) {Seitengröße} 
                    child {node [numeric] (pageSize10) {10} }
                    child {node [numeric] {25} }
                    child {node [numeric] (pageSize50) {50} }
                }
            }
            child [mandatory] { node [below = 2em] {Suchergebnis}
                child [mandatory] { node {Ergebnisvorschau} }
                child [mandatory] { node {Datum} }
                child [mandatory] { node {Dateityp}
                    child { node [value] {PDF} }
                    child { node [value] {DOCX} }
                    child { node [value] {HTML} }
                }
                child [mandatory] { node {Textinhalt} }
                child [mandatory] { node {Herkunft} }
            }
        }
        child [mandatory] { node [multiline] (browser) {Browser-\\unterstützung}
            child { node [value] (firefox) {firefox} }
            child { node [value] {chrome} }
            child { node [value] (safari) {safari} }
        }
    ;

    \alternative{pageSizes}{pageSize10}{pageSize50}
    \alternative{browser}{firefox}{safari}
    \alternative{sprachunterstuetzung}{englisch}{deutsch}
}
```
I hope it helps.

**Comment by codingfabi** [comment]
Oh thank you, that really solves the problem! Thanks very much :)
